### ISSUE TITLE
putsbox.com is taking too long, or never displaying emails

### ISSUE THREAD

**Issue by mikesnare** [phstc/putsbox#29]
Love the idea of putsbox, but so far it's not working for me.  I'm sending emails using cucumber/selenium/capybara tests and if I use a regular email, I get the emails.  But when I switch to putsbox I am unable to load them.  The don't show up on the bucket page, nor do they show up on the /last page.  Every now and then, they show up for a brief period of time, but they don't show up reliably enough for use in my tests.  Not sure if the site is just experiencing issues or what.  It's not a case of the emails being in flight since they come quickly to real addresses.  Just thought I'd let you know.

**Comment by phstc** [comment]
Hi @mikesnare 

Thanks a lot for reporting that. I've just tried a quick e-mail to pablo@putsbox.com and it showed up fine, but it does take a few seconds to show (SMTP).

Are you testing a specific e-mail? 

I don't think it is your problem, since you are using automated tests, but the e-mails are supposed to last for 15 minutes.

**Comment by mikesnare** [comment]
Sigh... I whitelisted this domain in the wrong staging environment.  That explains why the cuke tests (in env A) were not going out while regular emails sent from the console (in env B) were working fine.  Sorry about that.  Closing.
